# Generated by Django 5.2 on 2025-04-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='approval_date',
            field=models.DateField(null=True),
        ),
    ]
