# Generated by Django 5.2 on 2025-05-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0003_refund_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
