# Generated by Django 5.2 on 2025-05-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0004_alter_refund_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='approved',
        ),
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='refund',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
