# Generated by Django 5.2 on 2025-04-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
