# Generated by Django 5.2 on 2025-05-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('reprogramed', 'Reprogramed'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='active', max_length=20),
        ),
    ]
