# Generated by Django 5.2 on 2025-05-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('event', 'user')},
        ),
    ]
