# Generated by Django 5.2 on 2025-05-28 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_satisfaction', models.IntegerField(choices=[(1, 'Muy insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutro'), (4, 'Satisfecho'), (5, 'Muy satisfecho')], verbose_name='Satisfacción general')),
                ('purchase_experience', models.CharField(choices=[('muy_facil', 'Muy fácil'), ('facil', 'Fácil'), ('normal', 'Normal'), ('dificil', 'Difícil'), ('muy_dificil', 'Muy difícil')], max_length=20, verbose_name='Experiencia de compra')),
                ('would_recommend', models.BooleanField(verbose_name='¿Recomendarías este evento?')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_surveys', to='app.event')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_survey', to='app.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta de Satisfacción',
                'verbose_name_plural': 'Encuestas de Satisfacción',
                'ordering': ['-created_at'],
            },
        ),
    ]
