# Generated by Django 5.2 on 2025-05-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
