# Generated by Django 5.2 on 2025-05-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_events',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='app.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('canceled', 'Cancelado'), ('reprogramed', 'Reprogramado'), ('soldout', 'Agotado'), ('finished', 'Finalizado')], default='active', max_length=20),
        ),
    ]
