# Generated by Django 5.2 on 2025-05-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
