# Generated by Django 5.2 on 2025-05-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='card_type',
            field=models.CharField(choices=[('credit', 'Tarjeta de Credito'), ('debit', 'Tarjeta de Debito')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
