# Generated by Django 5.2 on 2025-04-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_venue_address_alter_venue_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(default=1, max_length=255, verbose_name='Ciudad'),
            preserve_default=False,
        ),
    ]
