# Generated by Django 5.2 on 2025-05-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ticket_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last4_card_number',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
