# Generated by Django 5.2 on 2025-04-24 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_date_event_scheduled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buy_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('general', 'General'), ('vip', 'VIP')], default='general', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
