# Generated by Django 5.2 on 2025-05-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notification_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.IntegerField()),
                ('issue', models.TextField(blank=True, null=True)),
                ('recommend', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.ticket')),
            ],
        ),
    ]
