# Generated by Django 5.2 on 2025-05-27 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_favorite_events_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='addressee',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.event'),
        ),
    ]
