# Generated by Django 5.2 on 2025-04-30 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_refoundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='refoundrequest',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='refound_requests', to='app.event'),
            preserve_default=False,
        ),
    ]
