# Generated by Django 5.2 on 2025-04-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_refundrequest_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='refundrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='accepted_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='ticket_code',
            field=models.CharField(max_length=255),
        ),
    ]
