# Generated by Django 5.2 on 2025-04-25 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aproved', models.BooleanField(default=False)),
                ('aproval_date', models.DateTimeField(blank=True, null=True)),
                ('ticket_code', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunded_tickets', to='app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunded_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
