# Generated by Django 5.1.1 on 2025-05-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('reprogramado', 'Reprogramado'), ('agotado', 'Agotado'), ('finalizado', 'Finalizado')], default='activo', max_length=20),
        ),
    ]
