# Generated by Django 5.2 on 2025-06-08 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_notification_addressee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="addressee",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="app.event",
            ),
        ),
    ]
