# Generated by Django 5.2 on 2025-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='titulo pendiente', max_length=100),
            preserve_default=False,
        ),
    ]
