# Generated by Django 5.2 on 2025-04-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_refundrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
