# Generated by Django 5.2 on 2025-05-15 23:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket_last4_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_general',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='price_vip',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
