# Generated by Django 5.2 on 2025-04-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_notification'),
        ('app', '0004_ticket'),
    ]

    operations = [
    ]
