# Generated by Django 5.2 on 2025-04-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_venue'),
        ('app', '0005_event_categories'),
    ]

    operations = [
    ]
