# Generated by Django 5.2 on 2025-04-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
