# Generated by Django 5.2 on 2025-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_favoriteevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('cancelled', 'Cancelado'), ('rescheduled', 'Reprogramado'), ('sold_out', 'Agotado'), ('finished', 'Finalizado')], default='active', help_text='Estado actual del evento', max_length=20),
        ),
    ]
