# Generated by Django 5.2 on 2025-05-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rating'),
        ('app', '0005_remove_event_category_event_categories_and_more'),
    ]

    operations = [
    ]
