# Generated by Django 5.2 on 2025-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='id_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
