# Generated by Django 5.2 on 2025-05-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket'),
        ('app', '0005_category_event_categories'),
    ]

    operations = [
    ]
