# Generated by Django 5.2 on 2025-05-15 23:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_event_price_general_event_price_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price_per_ticket',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
