# Generated by Django 5.2 on 2025-04-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_refoundrequest_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='refoundrequest',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
