# Generated by Django 5.2 on 2025-05-01 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_refundrequest_approved'),
        ('app', '0006_merge_0004_ticket_0005_category_event_categories'),
    ]

    operations = [
    ]
