# Generated by Django 5.2 on 2025-04-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comentario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Comment',
        ),
    ]
