# Generated by Django 5.2 on 2025-04-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_refoundrequest_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refoundrequest',
            name='details',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
