# Generated by Django 5.2 on 2025-04-29 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_comentario_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='texto',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='titulo',
            new_name='tittle',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.event'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
