# Generated by Django 5.2 on 2025-05-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_general_price_event_general_tickets_available_and_more'),
        ('app', '0007_merge_0006_event_venue_0006_merge_20250501_1139'),
    ]

    operations = [
    ]
