# Generated by Django 5.2 on 2025-05-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tickettype_ticket'),
        ('app', '0007_rating'),
    ]

    operations = [
    ]
