# Generated by Django 5.2 on 2025-05-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eventos_favoritos',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='app.event'),
        ),
    ]
