# Generated by Django 5.2 on 2025-04-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_code',
        ),
    ]
