# Generated by Django 5.2 on 2025-05-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
