# Generated by Django 5.2 on 2025-05-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(through='app.EventCategory', to='app.category'),
        ),
    ]
