# Generated by Django 5.2 on 2025-05-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_0004_tickettype_ticket_0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
