# Generated by Django 5.2 on 2025-05-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_notification_user_notificationxuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notificationxuser',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
