# Generated by Django 5.0 on 2025-05-02 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_notification_options_and_more'),
        ('app', '0008_alter_notification_options_and_more'),
    ]

    operations = [
    ]
