# Generated by Django 5.2 on 2025-04-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_notification_is_read_user_notification'),
        ('app', '0008_rename_texto_comment_text_and_more'),
    ]

    operations = [
    ]
