# Generated by Django 5.2 on 2025-05-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_eventos_favoritos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eventos_favoritos',
            new_name='favorite_events',
        ),
    ]
