# Generated by Django 5.2 on 2025-04-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ticket_refundrequest_delete_refoundrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='ticket_code',
            field=models.CharField(max_length=100),
        ),
    ]
