# Generated by Django 5.2 on 2025-05-27 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_ticket_quantity'),
        ('app', '0008_event_tickets_sold'),
    ]

    operations = [
    ]
