# Generated by Django 5.2 on 2025-05-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_notification_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
