# Generated by Django 5.2 on 2025-05-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rating'),
        ('app', '0009_merge_20250501_2320'),
    ]

    operations = [
    ]
