# Generated by Django 5.2 on 2025-04-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20250429_2248'),
        ('app', '0009_remove_event_category_event_categories'),
    ]

    operations = [
    ]
