# Generated by Django 5.2 on 2025-04-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='state',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='venue',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
