# Generated by Django 5.2 on 2025-04-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_refundrequest_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.CharField(choices=[('illness', 'Problemas de salud'), ('family_emergency', 'Emergencia familiar'), ('work_conflict', 'Compromisos laborales'), ('transport_issue', 'Problemas de transporte'), ('event_postponed', 'El evento fue pospuesto o cancelado'), ('other', 'Otro motivo')], max_length=20),
        ),
    ]
