# Generated by Django 5.2 on 2025-05-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_event_tickets_sold'),
        ('app', '0009_rename_eventos_favoritos_user_favorite_events'),
    ]

    operations = [
    ]
