# Generated by Django 5.2 on 2025-04-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_refundrequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.CharField(choices=[('Salud', 'Problemas de salud'), ('Emergencia Familiar', 'Emergencia familiar'), ('Trabajo', 'Compromisos laborales'), ('Transporte', 'Problemas de transporte'), ('Evento cancelado', 'El evento fue pospuesto o cancelado'), ('Otros', 'Otro motivo')], max_length=20),
        ),
    ]
