# Generated by Django 5.2 on 2025-04-30 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_venue_event_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('ticket_code', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RefundRequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
