# Generated by Django 5.2 on 2025-04-30 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_notification_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='addressee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
