# Generated by Django 5.2 on 2025-05-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_venue_event_venue'),
        ('app', '0010_merge_0006_rating_0009_merge_20250501_2320'),
    ]

    operations = [
    ]
