# Generated by Django 5.2 on 2025-04-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_refundrequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='approved',
            field=models.BooleanField(default=None),
        ),
    ]
