# Generated by Django 5.2 on 2025-04-30 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_refundrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300000)]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contact',
            field=models.TextField(max_length=200),
        ),
    ]
