# Generated by Django 5.0 on 2025-05-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_notification_options_notification_created_by_and_more'),
        ('app', '0011_merge_20250502_1159'),
    ]

    operations = [
    ]
