# Generated by Django 5.2 on 2025-05-02 19:08

from django.db import migrations

def crear_prioridades(apps, schema_editor):
    NotificationPriority = apps.get_model('app', 'NotificationPriority')
    NotificationPriority.objects.update_or_create(pk=1, defaults={"description": "Baja"})
    NotificationPriority.objects.update_or_create(pk=2, defaults={"description": "Media"})
    NotificationPriority.objects.update_or_create(pk=3, defaults={"description": "Alta"})

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_usernotification_notification_user'),
    ]

    operations = [
        migrations.RunPython(crear_prioridades),
    ]
