# Generated by Django 5.2 on 2025-04-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_refundrequest_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
