# Generated by Django 5.2 on 2025-05-01 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_refundrequest'),
        ('app', '0012_alter_venue_capacity_alter_venue_contact'),
    ]

    operations = [
    ]
