# Generated by Django 5.2 on 2025-05-02 19:33
from django.db import migrations

def load_notification_data(apps, schema_editor):
    Notification = apps.get_model('app', 'Notification')
    User = apps.get_model('app', 'User')
    Event = apps.get_model('app', 'Event') 
    NotificationPriority = apps.get_model('app', 'NotificationPriority')

    user1, created = User.objects.get_or_create(
        username='jperez', email='jperez@gmail.com', is_superuser=False, is_organizer=False
    )

    medium_priority = NotificationPriority.objects.filter(id=2).first()
    event1 = Event.objects.filter(id=1).first()

    if not medium_priority:
        medium_priority = None
    if not event1:
        event1 = None 

    # Crear notificación de prueba
    notification, created = Notification.objects.get_or_create(
        defaults={
            'title': '¡Recordatorio! Concierto de Jazz el 20 de junio',
            'message': '¡Recuerda que tu entrada para el Concierto de Jazz en el Teatro Central está confirmada! Nos vemos el 20 de junio a las 17:00. ¡No olvides traer tu entrada y disfrutar del evento!',
            'event': event1,
            'priority': medium_priority,
        }
    )

    notification.user.add(user1)  

def undo_notification_data(apps, schema_editor):
    Notification = apps.get_model('app', 'Notification')
    Notification.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20250502_1608'),
    ]

    operations = [
        migrations.RunPython(load_notification_data, undo_notification_data),
    ]
