# Generated by Django 5.2 on 2025-04-28 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rating'),
        ('app', '0012_alter_venue_capacity_ticket'),
    ]

    operations = [
    ]
