# Generated by Django 5.2 on 2025-04-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_refundrequest_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
