# Generated by Django 5.2 on 2025-05-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_event_available_tickets'),
        ('app', '0013_load_notification_data'),
    ]

    operations = [
    ]
