# Generated by Django 5.2 on 2025-05-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20250502_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='refund_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
