# Generated by Django 5.2 on 2025-04-29 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_0009_rating_0012_alter_venue_capacity_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='refoundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('refound_reason', models.CharField(choices=[('event_cancelled', 'Evento cancelado'), ('ticket_not_received', 'Entrada no recibida'), ('other', 'Otro')], default='other', max_length=50)),
                ('ticket_code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refound_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
