# Generated by Django 5.2 on 2025-05-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20250430_1944'),
        ('app', '0013_merge_20250430_2235'),
    ]

    operations = [
    ]
