# Generated by Django 5.2 on 2025-05-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_refundrequest_approval_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='code',
            new_name='ticket_dot',
        ),
    ]
