# Generated by Django 5.2 on 2025-05-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_code_ticket_ticket_dot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_dot',
            new_name='ticket_code',
        ),
    ]
