# Generated by Django 5.2.1 on 2025-05-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_notificationuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='users',
        ),
    ]
