# Generated by Django 5.2 on 2025-05-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
