# Generated by Django 5.2 on 2025-05-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20250502_0032'),
        ('app', '0018_delete_slide'),
    ]

    operations = [
    ]
