from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("accounts/register/", views.register, name="register"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("accounts/login/", views.login_view, name="login"),
    path("events/", views.events, name="events"),
    path("events/create/", views.event_form, name="event_form"),
    path("events/<int:id>/edit/", views.event_form, name="event_edit"),
    path("events/<int:id>/", views.event_detail, name="event_detail"),
    path("events/<int:id>/delete/", views.event_delete, name="event_delete"),
    path("tickets/", views.tickets, name="tickets"),
    path("tickets/create/<int:event_id>/", views.ticket_form, name="ticket_form"),
    path("tickets/<int:id>/", views.ticket_detail, name="ticket_detail"),
    path("tickets/<int:id>/update/", views.ticket_update, name="ticket_update"),
    path("tickets/<int:id>/delete/", views.ticket_delete, name="ticket_delete"),
    path("ticket_types/", views.ticket_types, name="ticket_types"),
    path("ticket_types/create/", views.ticket_type_form, name="ticket_type_form"),
    path("ticket_types/<int:id>/edit/", views.ticket_type_update, name="ticket_type_update"),
    path("ticket_types/<int:id>/delete/", views.ticket_type_delete, name="ticket_type_delete"),
    path("venues/", views.venues, name="venues"),
    path("venues/create/", views.venue_form,{"id": None},  name="venue_form"),
    path("venues/<int:id>/edit/", views.venue_form, name="venue_form"),
    path("venues/<int:id>/delete/", views.venue_delete, name="venue_delete"),
    path("venues/<int:id>/", views.venue_detail, name="venue_detail"),
    path("categories/", views.categories, name="categories"),
    path("categories/create/", views.category_form, name="category_create"),
    path("categories/<int:id>/edit/", views.category_form, name="category_update"),
    path("categories/<int:id>/delete/", views.category_delete, name="category_delete"),
    path("categories/<int:id>/", views.category_detail, name="category_detail"),
    path("events/<int:event_id>/rate/", views.rating_create_or_update, name="rating_create_or_update"),
    path("ratings/<int:id>/delete/", views.rating_delete, name="rating_delete"),
    path("notifications/", views.notifications, name="notifications"),
    path("notifications/create/", views.notification_form, name="notification_form"),
    path("notifications/<int:id>/edit/", views.notification_form, name="notification_edit"),
    path("notifications/<int:id>/delete/", views.notification_delete, name="notification_delete"),
    path("notifications/<int:id>/", views.notification_detail, name="notification_detail"),
    path('notifications/<int:notification_id>/read/', views.mark_notification_read, name='mark_read'),
    path('notifications/mark_all_read/', views.mark_all_notifications_read, name='mark_all_read'),
    path('comments/create/<int:event_id>/', views.comment_create, name='comment_create'),
    path('comments/edit/<int:comment_id>/', views.comment_edit, name='comment_edit'),
    path('comments/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]
