# Generated by Django 5.2 on 2025-05-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
