# Generated by Django 5.2 on 2025-05-26 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_categories'),
        ('tickets', '0002_alter_ticket_ticket_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('user', 'event')},
        ),
    ]
