name: Integración Continua - Eventhub

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build - Universidad Tecnológica Nacional Facultad Regional La Plata
    runs-on: ubuntu-latest

    steps:
        name: Checkout del código
        uses: actions/checkout@v3

        name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

        name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    name: Test Unitarios e Integración
    runs-on: ubuntu-latest
    needs: build

    steps:
        name: Checkout del código
        uses: actions/checkout@v3

        name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

        name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        name: Correr tests unitarios
        run: python manage.py test app.test.test_unit

        name: Correr tests de integración
        run: python manage.py test app.test.test_integration


  e2e:
    name: test End-to-End
    runs-on: ubuntu-latest
    needs: build

    steps:
        name: Checkout del código
        uses: actions/checkout@v3

        name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

        name: Instalar dependencias y Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install

        name: Correr tests E2E
        run: python manage.py test app.test.test_e2e
